version: '3.7'

services:
  backend:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run start:dev"
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mysql
    environment:
      TZ: 'Europe/Vienna'
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - htl_application-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: htl_application
      MYSQL_USER: htl_application
      MYSQL_PASSWORD: secret
    ports:
      - 3306:33060

  phpmyadmin:
      image: phpmyadmin
      environment:
        - PMA_ARBITRARY=1
      ports:
        - 8080:80

volumes:
  htl_application-mysql-data: